### ISSUE TITLE
Question - Access to package

### ISSUE THREAD

**Issue by gregsdennis** [alirezanet/publish-nuget#13]
I'd like to upload my packages as artifacts of the GH Action run, but the archive action can't find them.

For example, here's my action:

https://github.com/json-everything/json-everything/blob/83d7f6725c27f355904dbdf7d7badace10b76558/.github/workflows/publish-logic.yml#L27-L43

The `archive packages` step can't find any packages.

**Comment by GerardSmit** [comment]
This is because [`dotnet pack` is only executed when a new version has been found](https://github.com/alirezanet/publish-nuget/blob/e276c40afeb2a154046f0997820f2a9ea74832d9/index.js#L63-L78).

When looking at the [GitHub Action run of the commit](https://github.com/json-everything/json-everything/actions/runs/10419160455/job/28856643559), I don't see the message "✨ found new version", so it wasn't a new version and thus it didn't make any *.nupkg files.
